// <auto-generated />
using System;
using FodraszatIdopont.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FodraszatIdopont.Migrations
{
    [DbContext(typeof(BarberDbContext))]
    [Migration("20260305090852_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FodraszatIdopont.Models.Entities.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<int>("AppointmentStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("HairdresserId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AppointmentId");

                    b.HasIndex("HairdresserId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            AppointmentStatus = 0,
                            EndTime = new DateTime(2026, 3, 5, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = 4,
                            Notes = "Férfi hajvágás",
                            ServiceId = 2,
                            StartTime = new DateTime(2026, 3, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            AppointmentId = 2,
                            AppointmentStatus = 0,
                            EndTime = new DateTime(2026, 3, 5, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = 4,
                            Notes = "Női hajvágás",
                            ServiceId = 1,
                            StartTime = new DateTime(2026, 3, 5, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            AppointmentId = 3,
                            AppointmentStatus = 0,
                            EndTime = new DateTime(2026, 3, 5, 13, 45, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = 4,
                            Notes = "Hajfestés",
                            ServiceId = 3,
                            StartTime = new DateTime(2026, 3, 5, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            AppointmentId = 4,
                            AppointmentStatus = 0,
                            EndTime = new DateTime(2026, 3, 5, 15, 15, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = 4,
                            Notes = "Melírozás",
                            ServiceId = 4,
                            StartTime = new DateTime(2026, 3, 5, 13, 45, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            AppointmentId = 5,
                            AppointmentStatus = 0,
                            EndTime = new DateTime(2026, 3, 5, 16, 15, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = 4,
                            Notes = "Frizura készítés",
                            ServiceId = 5,
                            StartTime = new DateTime(2026, 3, 5, 15, 15, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            AppointmentId = 6,
                            AppointmentStatus = 0,
                            EndTime = new DateTime(2026, 3, 5, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = 4,
                            Notes = "Férfi hajvágás",
                            ServiceId = 2,
                            StartTime = new DateTime(2026, 3, 5, 16, 15, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            AppointmentId = 7,
                            AppointmentStatus = 0,
                            EndTime = new DateTime(2026, 3, 5, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = 4,
                            Notes = "Női hajvágás",
                            ServiceId = 1,
                            StartTime = new DateTime(2026, 3, 5, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            AppointmentId = 8,
                            AppointmentStatus = 0,
                            EndTime = new DateTime(2026, 3, 10, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = 5,
                            Notes = "Hajfestés délután",
                            ServiceId = 3,
                            StartTime = new DateTime(2026, 3, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            AppointmentId = 9,
                            AppointmentStatus = 0,
                            EndTime = new DateTime(2026, 3, 10, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = 5,
                            Notes = "Melírozás",
                            ServiceId = 4,
                            StartTime = new DateTime(2026, 3, 10, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            AppointmentId = 10,
                            AppointmentStatus = 0,
                            EndTime = new DateTime(2026, 3, 20, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = 4,
                            Notes = "Reggeli hajfestés",
                            ServiceId = 3,
                            StartTime = new DateTime(2026, 3, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            AppointmentId = 11,
                            AppointmentStatus = 0,
                            EndTime = new DateTime(2026, 3, 20, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = 4,
                            Notes = "Délutáni női hajvágás",
                            ServiceId = 1,
                            StartTime = new DateTime(2026, 3, 20, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            AppointmentId = 12,
                            AppointmentStatus = 0,
                            EndTime = new DateTime(2026, 3, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = 5,
                            Notes = "Frizura reggel",
                            ServiceId = 5,
                            StartTime = new DateTime(2026, 3, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            AppointmentId = 13,
                            AppointmentStatus = 0,
                            EndTime = new DateTime(2026, 3, 15, 14, 45, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = 5,
                            Notes = "Férfi hajvágás délután",
                            ServiceId = 2,
                            StartTime = new DateTime(2026, 3, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("FodraszatIdopont.Models.Entities.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<int>("DurationInMinute")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("ServiceId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            DurationInMinute = 60,
                            Name = "Női hajvágás",
                            Price = 6000,
                            isActive = true
                        },
                        new
                        {
                            ServiceId = 2,
                            DurationInMinute = 45,
                            Name = "Férfi hajvágás",
                            Price = 4000,
                            isActive = true
                        },
                        new
                        {
                            ServiceId = 3,
                            DurationInMinute = 120,
                            Name = "Hajfestés",
                            Price = 15000,
                            isActive = true
                        },
                        new
                        {
                            ServiceId = 4,
                            DurationInMinute = 90,
                            Name = "Melírozás",
                            Price = 12000,
                            isActive = true
                        },
                        new
                        {
                            ServiceId = 5,
                            DurationInMinute = 60,
                            Name = "Frizura készítés",
                            Price = 7000,
                            isActive = true
                        });
                });

            modelBuilder.Entity("FodraszatIdopont.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin",
                            Name = "admin",
                            PasswordHash = "100000.xJee9rsJ3BCY6B67PjDVAg==.pOLyoXHmCIN1zXEgoZ5gH3T05SfsXE1Y1DW+l14SJPo=",
                            Role = 4,
                            Sex = 0
                        },
                        new
                        {
                            UserId = 2,
                            Email = "anna.kovacs@gmail.com",
                            Name = "Anna Kovács",
                            PasswordHash = "100000.Yli5RTvANw7/z1l80OGgWg==.fW6ppLLGuX8tZZ8/B5949wT5xBZ6QKGjN4+7thH2Rbk=",
                            Role = 1,
                            Sex = 2
                        },
                        new
                        {
                            UserId = 3,
                            Email = "peter.nagy@gmail.com",
                            Name = "Péter Nagy",
                            PasswordHash = "100000.vdBl0bsVopLQKNX3Wlj/sg==.obDhu6r2uVmuag8gBVVvYJyDEU85gWeoctYFokSZVuc=",
                            Role = 1,
                            Sex = 1
                        },
                        new
                        {
                            UserId = 4,
                            Email = "gabor.fodrasz@gmail.com",
                            Name = "Nagy Gábor",
                            PasswordHash = "100000.n8xtN489r42l7WtfMmmmfw==.7Fy7c9tYeVJAHtf9NfePLhZ6L4yV+3BSyOnkwRJ+fsk=",
                            Role = 2,
                            Sex = 2
                        },
                        new
                        {
                            UserId = 5,
                            Email = "marcell.fodrasz@gmail.com",
                            Name = "Belák Marcell",
                            PasswordHash = "100000.MpbNpQCRUnK3K9DA+OhEhw==.ZQSk5zQtP4t262wwW6Ed8VGqoJaToxZNXRAhFBuJXVI=",
                            Role = 2,
                            Sex = 1
                        });
                });

            modelBuilder.Entity("FodraszatIdopont.Models.Entities.Appointment", b =>
                {
                    b.HasOne("FodraszatIdopont.Models.Entities.User", "Hairdresser")
                        .WithMany("HairdresserAppointments")
                        .HasForeignKey("HairdresserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FodraszatIdopont.Models.Entities.Service", "Service")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FodraszatIdopont.Models.Entities.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hairdresser");

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FodraszatIdopont.Models.Entities.Service", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("FodraszatIdopont.Models.Entities.User", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("HairdresserAppointments");
                });
#pragma warning restore 612, 618
        }
    }
}
