// <auto-generated />
using System;
using FodraszatIdopont.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FodraszatIdopont.Migrations
{
    [DbContext(typeof(BarberDbContext))]
    [Migration("20260302112205_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FodraszatIdopont.Models.Entities.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<int>("AppointmentStatus")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("HairdresserId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AppointmentId");

                    b.HasIndex("HairdresserId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("FodraszatIdopont.Models.Entities.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<int>("DurationInMinute")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("ServiceId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            DurationInMinute = 60,
                            Name = "Női hajvágás",
                            Price = 6000,
                            isActive = true
                        },
                        new
                        {
                            ServiceId = 2,
                            DurationInMinute = 45,
                            Name = "Férfi hajvágás",
                            Price = 4000,
                            isActive = true
                        },
                        new
                        {
                            ServiceId = 3,
                            DurationInMinute = 120,
                            Name = "Hajfestés",
                            Price = 15000,
                            isActive = true
                        },
                        new
                        {
                            ServiceId = 4,
                            DurationInMinute = 90,
                            Name = "Melírozás",
                            Price = 12000,
                            isActive = true
                        },
                        new
                        {
                            ServiceId = 5,
                            DurationInMinute = 60,
                            Name = "Frizura készítés",
                            Price = 7000,
                            isActive = true
                        });
                });

            modelBuilder.Entity("FodraszatIdopont.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin",
                            Name = "admin",
                            PasswordHash = "100000.mEabUMHOzNcI9WB/KT4VdA==.FfYF1tCJo/1N3JhTsxMgoy9aMa4JnMizC/2V7kDek2E=",
                            Role = 4,
                            Sex = 0
                        },
                        new
                        {
                            UserId = 2,
                            Email = "anna.kovacs@gmail.com",
                            Name = "Anna Kovács",
                            PasswordHash = "100000.yuczWUwlLNtGQPeeRALcSw==.69camw4RQIwaFLC0Nja0rr/CvHFZMwTFuFX7kE2sT4M=",
                            Role = 1,
                            Sex = 2
                        },
                        new
                        {
                            UserId = 3,
                            Email = "peter.nagy@gmail.com",
                            Name = "Péter Nagy",
                            PasswordHash = "100000.cmaT/7+hSczl/Vljd1RhpA==.yRICHU0JRKIfFEnnnOXqCclxaXJHSAyhC0gLGOaDWK8=",
                            Role = 1,
                            Sex = 1
                        },
                        new
                        {
                            UserId = 4,
                            Email = "eszter.fodrasz@gmail.com",
                            Name = "Eszter Fodrász",
                            PasswordHash = "100000.u0cbJvNnlmVBSs4kqmduAg==./ZEYmSE1468c2pBJp27DcH6XD3Nh2/eov2dIUf5QDaE=",
                            Role = 2,
                            Sex = 2
                        },
                        new
                        {
                            UserId = 5,
                            Email = "gabor.fodrasz@gmail.com",
                            Name = "Gábor Fodrász",
                            PasswordHash = "100000.F3hEuPibdr8ARoeuVj1V+A==.MZ6TIHP0hV6O6wxzmL1jRpsm4fypz8WUhb8sChK78LY=",
                            Role = 2,
                            Sex = 1
                        });
                });

            modelBuilder.Entity("FodraszatIdopont.Models.Entities.Appointment", b =>
                {
                    b.HasOne("FodraszatIdopont.Models.Entities.User", "Hairdresser")
                        .WithMany("HairdresserAppointments")
                        .HasForeignKey("HairdresserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FodraszatIdopont.Models.Entities.Service", "Service")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FodraszatIdopont.Models.Entities.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hairdresser");

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FodraszatIdopont.Models.Entities.Service", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("FodraszatIdopont.Models.Entities.User", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("HairdresserAppointments");
                });
#pragma warning restore 612, 618
        }
    }
}
