// <auto-generated />
using System;
using FodraszatIdopont.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FodraszatIdopont.Migrations
{
    [DbContext(typeof(BarberDbContext))]
    partial class BarberDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FodraszatIdopont.Models.Entities.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<int>("AppointmentStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("HairdresserId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AppointmentId");

                    b.HasIndex("HairdresserId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("FodraszatIdopont.Models.Entities.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<int>("DurationInMinute")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("ServiceId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            DurationInMinute = 60,
                            Name = "Női hajvágás",
                            Price = 6000,
                            isActive = true
                        },
                        new
                        {
                            ServiceId = 2,
                            DurationInMinute = 45,
                            Name = "Férfi hajvágás",
                            Price = 4000,
                            isActive = true
                        },
                        new
                        {
                            ServiceId = 3,
                            DurationInMinute = 120,
                            Name = "Hajfestés",
                            Price = 15000,
                            isActive = true
                        },
                        new
                        {
                            ServiceId = 4,
                            DurationInMinute = 90,
                            Name = "Melírozás",
                            Price = 12000,
                            isActive = true
                        },
                        new
                        {
                            ServiceId = 5,
                            DurationInMinute = 60,
                            Name = "Frizura készítés",
                            Price = 7000,
                            isActive = true
                        });
                });

            modelBuilder.Entity("FodraszatIdopont.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin",
                            Name = "admin",
                            PasswordHash = "100000.uIQCkKIytRzQzmnWr149Eg==.eRs1py3glW0wYeeLhhibO01obWvhPAYXhCq0SiJVKZA=",
                            Role = 4,
                            Sex = 0
                        },
                        new
                        {
                            UserId = 2,
                            Email = "anna.kovacs@gmail.com",
                            Name = "Anna Kovács",
                            PasswordHash = "100000.l4KQxN+h2ZK0FtSfLqYCig==.GbjF/jnaMEuSPAnLGINvG1x+y/7uuL8ICr0sf/4vzRc=",
                            Role = 1,
                            Sex = 2
                        },
                        new
                        {
                            UserId = 3,
                            Email = "peter.nagy@gmail.com",
                            Name = "Péter Nagy",
                            PasswordHash = "100000.iUvYEck75icum7zeWwOAmw==.LjDxnXNQlRluprVW8EiKJql5SH1wJErJRickDnG53pA=",
                            Role = 1,
                            Sex = 1
                        },
                        new
                        {
                            UserId = 4,
                            Email = "eszter.fodrasz@gmail.com",
                            Name = "Eszter Fodrász",
                            PasswordHash = "100000.AO/PktcrFjnlcfYiz/souA==.s1H04A/7lq9wwkRYLGxCPmb3ad6Mhu0bYqveAYN9NaA=",
                            Role = 2,
                            Sex = 2
                        },
                        new
                        {
                            UserId = 5,
                            Email = "gabor.fodrasz@gmail.com",
                            Name = "Gábor Fodrász",
                            PasswordHash = "100000.VavK9K+Hf2tVqx88HNJP+w==.PWqfHTJ503VZ+LFgRj2862b3Tg0kmfMKMBo3+sK6evQ=",
                            Role = 2,
                            Sex = 1
                        });
                });

            modelBuilder.Entity("FodraszatIdopont.Models.Entities.Appointment", b =>
                {
                    b.HasOne("FodraszatIdopont.Models.Entities.User", "Hairdresser")
                        .WithMany("HairdresserAppointments")
                        .HasForeignKey("HairdresserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FodraszatIdopont.Models.Entities.Service", "Service")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FodraszatIdopont.Models.Entities.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hairdresser");

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FodraszatIdopont.Models.Entities.Service", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("FodraszatIdopont.Models.Entities.User", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("HairdresserAppointments");
                });
#pragma warning restore 612, 618
        }
    }
}
