// <auto-generated />
using System;
using FodraszatIdopont.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FodraszatIdopont.Migrations
{
    [DbContext(typeof(BarberDbContext))]
    partial class BarberDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FodraszatIdopont.Models.Entities.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<int>("AppointmentStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("HairdresserId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AppointmentId");

                    b.HasIndex("HairdresserId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            AppointmentStatus = 0,
                            EndTime = new DateTime(2026, 4, 10, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = 2,
                            ServiceId = 1,
                            StartTime = new DateTime(2026, 4, 10, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            AppointmentId = 2,
                            AppointmentStatus = 0,
                            EndTime = new DateTime(2026, 4, 10, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = 2,
                            ServiceId = 2,
                            StartTime = new DateTime(2026, 4, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            AppointmentId = 3,
                            AppointmentStatus = 2,
                            EndTime = new DateTime(2025, 12, 15, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = 3,
                            ServiceId = 1,
                            StartTime = new DateTime(2025, 12, 15, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            AppointmentId = 4,
                            AppointmentStatus = 1,
                            EndTime = new DateTime(2025, 11, 20, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = 3,
                            ServiceId = 3,
                            StartTime = new DateTime(2025, 11, 20, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        },
                        new
                        {
                            AppointmentId = 5,
                            AppointmentStatus = 0,
                            EndTime = new DateTime(2026, 4, 12, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = 2,
                            ServiceId = 2,
                            StartTime = new DateTime(2026, 4, 12, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1
                        },
                        new
                        {
                            AppointmentId = 6,
                            AppointmentStatus = 2,
                            EndTime = new DateTime(2025, 10, 5, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = 3,
                            ServiceId = 1,
                            StartTime = new DateTime(2025, 10, 5, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            UserId = 5
                        },
                        new
                        {
                            AppointmentId = 7,
                            AppointmentStatus = 0,
                            EndTime = new DateTime(2026, 4, 13, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = 4,
                            ServiceId = 3,
                            StartTime = new DateTime(2026, 4, 13, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2
                        },
                        new
                        {
                            AppointmentId = 8,
                            AppointmentStatus = 2,
                            EndTime = new DateTime(2025, 9, 18, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = 4,
                            ServiceId = 2,
                            StartTime = new DateTime(2025, 9, 18, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 3
                        },
                        new
                        {
                            AppointmentId = 9,
                            AppointmentStatus = 0,
                            EndTime = new DateTime(2026, 4, 14, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = 2,
                            ServiceId = 1,
                            StartTime = new DateTime(2026, 4, 14, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 4
                        },
                        new
                        {
                            AppointmentId = 10,
                            AppointmentStatus = 1,
                            EndTime = new DateTime(2025, 8, 22, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            HairdresserId = 3,
                            ServiceId = 3,
                            StartTime = new DateTime(2025, 8, 22, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 5
                        });
                });

            modelBuilder.Entity("FodraszatIdopont.Models.Entities.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<int>("DurationInMinute")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("ServiceId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            DurationInMinute = 60,
                            Name = "Női hajvágás",
                            Price = 6000,
                            isActive = true
                        },
                        new
                        {
                            ServiceId = 2,
                            DurationInMinute = 45,
                            Name = "Férfi hajvágás",
                            Price = 4000,
                            isActive = true
                        },
                        new
                        {
                            ServiceId = 3,
                            DurationInMinute = 120,
                            Name = "Hajfestés",
                            Price = 15000,
                            isActive = true
                        },
                        new
                        {
                            ServiceId = 4,
                            DurationInMinute = 90,
                            Name = "Melírozás",
                            Price = 12000,
                            isActive = true
                        },
                        new
                        {
                            ServiceId = 5,
                            DurationInMinute = 60,
                            Name = "Frizura készítés",
                            Price = 7000,
                            isActive = true
                        });
                });

            modelBuilder.Entity("FodraszatIdopont.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int>("Sex")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Email = "admin",
                            Name = "admin",
                            PasswordHash = "100000.N2u9Ytm/+h17JxxBZHgyKg==.45Qb88rM+mjEbCCwjyxXKyxtRExahnaLPO/QOtxfYi8=",
                            Role = 4,
                            Sex = 0
                        },
                        new
                        {
                            UserId = 2,
                            Email = "anna.kovacs@gmail.com",
                            Name = "Anna Kovács",
                            PasswordHash = "100000.clx32FeirbAjWwF9thxz6w==.vCMU7ZuAQIEzQtb4svDByiBfzAdRoq0E4EBSKhoRSBk=",
                            Role = 1,
                            Sex = 2
                        },
                        new
                        {
                            UserId = 3,
                            Email = "peter.nagy@gmail.com",
                            Name = "Péter Nagy",
                            PasswordHash = "100000.lg2qwi6lAll6TWCHQxh3aA==.6p8UAfn1l2wCWoTnMr9pTbjJLJRDoy2BLzh1ADGanEY=",
                            Role = 1,
                            Sex = 1
                        },
                        new
                        {
                            UserId = 4,
                            Email = "gabor.fodrasz@gmail.com",
                            Name = "Nagy Gábor",
                            PasswordHash = "100000.bTTyZUi0jj6aPQ2q53n7Mg==.702A+Wu9tnbpvC0I2WEvmzkxktMSunXWezOoqKQfLQs=",
                            Role = 2,
                            Sex = 2
                        },
                        new
                        {
                            UserId = 5,
                            Email = "marcell.fodrasz@gmail.com",
                            Name = "Belák Marcell",
                            PasswordHash = "100000.7/kIc+smoq/Q+kH6K2lcGw==.rDGaTVLARvmEX/HXqcCrFch1mfTUygUDYdZa4NGt8UE=",
                            Role = 2,
                            Sex = 1
                        });
                });

            modelBuilder.Entity("FodraszatIdopont.Models.Entities.Appointment", b =>
                {
                    b.HasOne("FodraszatIdopont.Models.Entities.User", "Hairdresser")
                        .WithMany("HairdresserAppointments")
                        .HasForeignKey("HairdresserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FodraszatIdopont.Models.Entities.Service", "Service")
                        .WithMany("Appointments")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FodraszatIdopont.Models.Entities.User", "User")
                        .WithMany("Appointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hairdresser");

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FodraszatIdopont.Models.Entities.Service", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("FodraszatIdopont.Models.Entities.User", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("HairdresserAppointments");
                });
#pragma warning restore 612, 618
        }
    }
}
